config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users

  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  match '/user/info', to:'users/profiles#info',via: :get, as: :user_info
  match '/user/info/update', to:'users/profiles#update_info',via: :post, as: :update_info
  match '/user/avatar', to:'users/profiles#avatar',via: :get, as: :user_avatar
  match '/user/avatar/update', to:'users/profiles#update_avatar',via: :post, as: :update_avatar

  namespace :admin do
    resources :file_sources
    resources :users
  end

end

app/models/user.rb
# t.string   "email",                  limit: 255, default: "", null: false
# t.string   "encrypted_password",     limit: 255, default: "", null: false
# t.integer  "role",                   limit: 4,   default: 1
# t.string   "reset_password_token",   limit: 255
# t.datetime "reset_password_sent_at"
# t.datetime "remember_created_at"
# t.integer  "sign_in_count",          limit: 4,   default: 0,  null: false
# t.datetime "current_sign_in_at"
# t.datetime "last_sign_in_at"
# t.string   "current_sign_in_ip",     limit: 255
# t.string   "last_sign_in_ip",        limit: 255
# t.string   "nick_name",              limit: 255
# t.string   "avatar",                 limit: 255
# t.string   "phone",                  limit: 255
# t.string   "location",               limit: 255

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :set_admin
  scope :recent, -> {order(updated_at: :desc)}
  self.per_page = 10

  def admin?
    return true if self.role == 0
    return false
  end

  def set_admin
    self.update_attributes(role:0) if User.where(role:0).count == 0
  end

  def set_nick_name
    self.nick_name = self.email.split('@')[0]
  end

  def display_name
    return self.nick_name if self.nick_name.present?
    return self.email.split('@')[0]
  end

  def self.baidu_location(ip)
    baidu_json = $baidu_location.get do |req|
      req.url '/location/ip'
      req.params['ip'] = ip
      req.params['ak'] = '5PELDwT7pnzGDOjTjrV5oGq8'
    end
    body = JSON.parse(baidu_json.body)
    return body['content']['address'] if body['status'] == 0
    return '地球村'
  end

  # User.cx_location('')
  def self.cx_location(ip)
    url = 'http://api.ip138.com/query/'
    app_code = 'f910da9ce9ac0b40625c43f372363fac'
    res = Faraday.get do |req|
      req.url url
      req.params[:ip] = ip
      req.headers[:token] = app_code
    end
    info = JSON.parse(res.body)
    address = info['data']
    return zh_location(address[0],address[1],address[2]) if info['ret'] == 'ok'
    return baidu_location(ip)
  end

  def self.zh_location(coun,prov,city)
    if coun != prov && prov != city
      return coun + prov + city
    elsif coun == prov
      return coun + city
    elsif prov == city
      return coun + city
    end
  end

  def role_name
    {0=>'老司机',1=>'小盆友',2=>'鉴黄师'}[self.role]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    query = params[:query]
    @users = User.recent
    @users = @users.where("email LIKE '%#{query}%' OR nick_name LIKE '%#{query}%'") if query.present?
    @users = @users.paginate(:page => params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = '用户信息更新成功！'
      redirect_to admin_users_path
    else
      flash[:warn] = '请完善填写表单内容'
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = '用户信息删除成功'
    redirect_to :back
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:role)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'user'

  # GET /forgot_password
  def new
    super
  end

  #POST /forgot_password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      redirect_to sign_in_path
    else
      render :new
    end
  end

  # GET /reset_password?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /reset_password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?
    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_flashing_format?
      sign_in(resource_name, resource)
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      render :edit
    end
  end

end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_filter :authenticate_user!
  layout 'user'

  def avatar
  end

  def update_avatar
    if params[:avatar]
      file = Base64.decode64(params[:avatar]['data:image/png;base64,'.length .. -1])
      cover = FileSource.save_avatar(file)
      current_user.avatar = cover.file_path
      current_user.save
      redirect_to root_path
    else
      render :avatar
    end
  end

  def info
  end

  def update_info
    current_user.nick_name = params[:nick_name]
    current_user.phone = params[:phone]
    current_user.save
    redirect_to user_info_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'user'
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  #GET /resource/sign_up

  def new
    super
  end

  #POST /resource
  def create
    build_resource(sign_up_params)

    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      render :new
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'user'

  def new
  end

  # POST /resource/sign_in
  def create
    user = User.find_by_email(params[:user][:email])
    if params[:user][:email].blank? || params[:user][:password].blank?
      flash[:email] = "邮箱或密码为空"
      render :new
    elsif !user
      new = User.create(new_params)
      sign_in(new)
      redirect_to root_path
    elsif user && !user.valid_password?(params[:user][:password])
      flash[:password] = "密码错误"
      flash[:set_email] = params[:user][:email]
      render :new
    else
      sign_in(user)
      flash[:notice] = (t 'devise.sessions.signed_in')
      redirect_to root_path
    end
  end

  private

    def new_params
      params.require(:user).permit(:email, :password)
    end

end

app/views/users/profiles/avatar.html.erb
<%= content_for(:title, '上传头像 | Koogle') %>
<div class="login">
  <div class="imageBox">
    <div class="thumbBox"></div>
  </div>
  <form method="post" action="<%= update_avatar_path %>">
    <div class="imageAction">
      <div class="imageUpload">
        <a class="upload-img">
          <label>选择头像</label>
        </a>
        <input type="file" class="file_input" name="file" id="upload-file" />
        <input type="hidden" id="data" name="avatar"/>
      </div>
      <div class="imageCrop">
        <a id="btnZoomOut" class="Btnsty_out"><i class="fa fa-minus"></i></a>
        <a id="btnZoomIn" class="Btnsty_in"><i class="fa fa-plus"></i></a>
        <a id="btnCrop"  class="Btnsty_yes"><i class="fa fa-check"></i></a>
      </div>
    </div>
    <div class="imagePre">
      <div class="pre_right">
        <img src="<%= display_avatar current_user %>" class="pre_square">
      </div>
      <div class="pre_left">
        <img src="<%= display_avatar current_user %>" class="pre_round">
      </div>
    </div>
    <div class="cropUpload">
      <input type="submit" disabled="disabled" class="login__submit" value="上传头像">
    </div>
  </form>
<div>
<%= content_for :javascript do %>
<script type="text/javascript">
  $(function(){
    var options = {thumbBox: '.thumbBox'}
    var cropper = $('.imageBox').cropbox(options);
    $('#upload-file').on('change', function(){
      var reader = new FileReader();
      reader.onload = function(e) {
        options.imgSrc = e.target.result;
        cropper = $('.imageBox').cropbox(options);
      }
      reader.readAsDataURL(this.files[0]);
    })
    $('#btnZoomIn').on('click', function(){
      cropper.zoomIn();
    })
    $('#btnZoomOut').on('click', function(){
      cropper.zoomOut();
    })
    $('#btnCrop').on('click', function(){
      var img = cropper.getDataURL();
      $('.pre_round').attr('src',img);
      $('.pre_square').attr('src',img);
      $('#data').val(img);
      $('.login__submit').removeAttr('disabled');
    })
  });
</script>
<% end -%>

app/views/users/profiles/info.html.erb
<%= content_for(:title, '我的信息 | Koogle') %>
<div class="login">
  <div style="text-align: center;padding-top: 30px;">
    <img src="<%= display_avatar current_user %>" style="height: 100px;border-radius: 50%;">
  </div>
  <div class="login__form" style="margin-top: -50px;">
    <form method="post" action="<%= update_info_path %>">
      <div class="login__row">
        <div class="ion-icon"><i class="ion ion-ios-chatboxes-outline"></i></div>
        <input style="padding-left: 30px;color: #FFCC33;" type="text" name="nick_name" value="<%= current_user.nick_name %>" class="login__input name" placeholder="个性昵称">
      </div>
      <div class="login__row">
        <div class="ion-icon"><i class="ion ion-ios-email-outline"></i></div>
        <input style="padding-left: 30px;color: #CCFF33;" type="text" value="<%= current_user.email %>" class="login__input name" placeholder="邮箱账户">
      </div>
      <div class="login__row">
        <div class="ion-icon"><i class="ion ion-ios-telephone-outline"></i></div>
        <input style="padding-left: 30px;color: #FF6666;" type="text" name="phone" value="<%= current_user.phone %>" class="login__input name" placeholder="联系方式">
      </div>
      <div class="login__row">
        <div class="ion-icon"><i class="ion ion-ios-location-outline"></i></div>
        <input style="padding-left: 30px;color: #FFFF33;" type="text" value="<%= current_user.current_sign_in_ip %>" class="login__input name" placeholder="地理位置">
      </div>
      <button id="submit" type="submit" class="login__submit">更新资料</button>
    </form>
  </div>
</div>