config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users

  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  match '/user/info', to:'users/profiles#info',via: :get, as: :user_info
  match '/user/info/update', to:'users/profiles#update_info',via: :post, as: :update_info
  match '/user/avatar', to:'users/profiles#avatar',via: :get, as: :user_avatar
  match '/user/avatar/update', to:'users/profiles#update_avatar',via: :post, as: :update_avatar

  namespace :admin do
    resources :file_sources
    resources :users
  end

end

app/models/file_source.rb
    # t.string   "file_name",  limit: 255
    # t.string   "file_type",  limit: 255
    # t.string   "file_size",  limit: 255
    # t.string   "file_md5",   limit: 255
    # t.string   "file_path",  limit: 255
require 'digest'

class FileSource < ActiveRecord::Base
  attr_accessor :local_file
  scope :latest, -> { order(created_at: :desc) }
  self.per_page = 15

  def self.save_file(file)
    ext = file.original_filename.split('.')[-1]
    name = file_name(25,ext)
    md5 = Digest::MD5.hexdigest(File.read(file.path))
    unless FileSource.find_by_file_md5(md5)
      torrent = FileSource.new
      torrent.file_name = name
      torrent.file_type = ext
      torrent.file_size = file.size
      torrent.file_md5 = md5
      torrent.file_path = "storage/#{ext}/#{name}"
      torrent.save
    end
    torrent = FileSource.find_by_file_md5(md5)
    file_store(file,torrent.file_name,torrent.file_type)
    torrent
  end

  def self.save_avatar(file)
    ext = 'png'
    name = file_name(25,ext)
    md5 = Digest::MD5.hexdigest(file)
    avatar = FileSource.new
    avatar.file_name = name
    avatar.file_type = 'avatar'
    avatar.file_size = file.size
    avatar.file_md5 = md5
    avatar.file_path = "storage/avatar/#{name}"
    avatar.save
    avatar_store_local(file,avatar.file_name,avatar.file_type)
    avatar
  end

  def self.file_store(file,name,directory)
    full_path = file_directory(directory) + name
    unless File.exist?(full_path)
      File.open(full_path, 'wb+') do |item|
        item.write(file.read)
      end
    end
  end

  def self.avatar_store_local(file,name,directory)
    full_path = file_directory(directory) + name
    unless File.exist?(full_path)
      File.open(full_path, 'wb+') do |item|
        item.write(file)
      end
    end
  end

  def self.file_name(length,ext)
    return "#{rand_string(25)}.#{ext}"
  end

  def self.file_directory(directory)
    root_path = "#{Rails.root}/public/storage/" #软链文件 授权 chmod -R 777 uploads
    file_path = root_path + directory + '/'
    FileUtils.mkdir_p(file_path) unless File.exist?(file_path) #如果目录不存在,创建目录
    file_path
  end

  def self.rand_string(length)
    return [*'1'..'9',*'a'..'z',*'A'..'Z'].sample(length.to_i).join('')
  end

  def clean
    local_path = "#{Rails.root}/public/#{self.file_path}"
    if File.exist?(local_path)
      File.delete(local_path)
    end
  end

end

app/controllers/admin/file_sources_controller.rb
class Admin::FileSourcesController < Admin::BaseController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  def index
    query = params[:query]
    @sources = FileSource.latest
    @sources = @sources.where("file_name LIKE '%#{query}%'") if query.present?
    @sources = @sources.paginate(:page => params[:page])
  end

  def new
    @source = FileSource.new
  end

  def edit
  end

  def create
    @source = FileSource.save_file(params[:file_source][:local_file])
    if @source
      flash[:success] = '文件样品创建成功！'
      redirect_to admin_file_sources_path
    else
      flash[:warn] = '请完善填写表单内容'
      render :new
    end
  end

  def update
    if @source.update_attributes(file_source_params)
      flash[:notice] = '文件样品更新成功！'
      redirect_to admin_file_sources_path
    else
      flash[:warn] = '请完善填写表单内容'
      render :edit
    end
  end

  def destroy
    @source.clean
    @source.destroy
    flash[:notice] = '文件样品删除成功'
    redirect_to :back
  end

  private
    def set_source
      @source = FileSource.find(params[:id])
    end

    def file_source_params
      params.require(:file_source).permit(:file_name, :file_type, :file_size, :file_md5, :file_path)
    end
end

app/views/admin/file_sources/_form.html.erb
<%= form_for(['admin',@source]) do |f| %>
<div class="box-body">
  <div class="col-md-5">
  <% if action_name == 'new' %>
    <div class="form-group has-error">
      <label>本地文件</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-fa"></i>
        </div>
        <%= f.file_field :local_file, class:'form-control' %>
      </div>
    </div>
  <% else %>
    <div class="form-group has-success">
      <label>名称</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-file-word-o"></i>
        </div>
        <%= f.text_field :file_name, class:'form-control', placeholder:'（必填* ）' %>
      </div>
    </div>
    <div class="form-group has-success">
      <label>类型</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-flag"></i>
        </div>
        <%= f.text_field :file_type, class:'form-control', placeholder:'（必填* ）' %>
      </div>
    </div>
    <div class="form-group has-success">
      <label>大小</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-gear"></i>
        </div>
        <%= f.text_field :file_size, class:'form-control', placeholder:'（必填* ）' %>
      </div>
    </div>
    <div class="form-group has-success">
      <label>值块</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-file-code-o"></i>
        </div>
        <%= f.text_field :file_md5, class:'form-control', placeholder:'（必填* ）' %>
      </div>
    </div>
    <div class="form-group has-success">
      <label>路径</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-folder-o"></i>
        </div>
        <%= f.text_field :file_path, class:'form-control', placeholder:'（必填* ）' %>
      </div>
    </div>
  <% end %>
  </div>
  <div class="col-md-12">
    <hr>
    <div>
      <button type="submit" class="btn bg-maroon btn-flat" style="width: 120px">提交</button>
      <a href="<%= admin_file_sources_path %>" class="btn bg-navy btn-flat" style="width: 120px">取消</a>
    </div>
  </div>
</div>
<% end %>

app/views/admin/file_sources/edit.html.erb
<%= content_for(:title,  '编辑文件信息| Master') %>
<section class="content-header">
  <h1>
    编辑文件信息
  </h1>
  <ol class="breadcrumb">
    <li><i class="glyphicon glyphicon-edit"></i> 编辑文件信息</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-warning">
      <div class="box-header">
        <h3 class="box-title">编辑表单</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section><!-- END PAGE CONTENT -->

app/views/admin/file_sources/index.html.erb
<%= content_for(:title,  '文件管理列表 | Master') %>
<section class="content-header">
  <h1>
    文件管理 <small>信息预览</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><i class="fa fa-bicycle"></i> 文件管理</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
      <div class="row">
        <div class="col-sm-4">
          <form action="<%= admin_file_sources_path %>" method="get">
            <div class="form-group has-feedback">
              <div class="input-group">
                <input type="text" name="query" value="<%= params[:query]%>" class="form-control" placeholder="名称">
                <span class="input-group-btn">
                  <button class="btn btn-default btn-flat" type="submit"><i class="fa fa-search-plus"></i></button>
                </span>
              </div>
            </div>
          </form>
        </div>
        <div class="col-sm-8">
          <a href="<%= new_admin_file_source_path %>" class="btn bg-primary btn-flat" style="float: right;"><i class="ion-plus"></i> 添加样品</a>
        </div>
      </div>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-sm-12">
          <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
            <thead>
            <tr>
              <th tabindex="0" aria-controls="example1" style="text-align: center;">名称</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;">类型</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;">大小</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;">路径</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;width: 200px">操作</th>
            </tr>
            </thead>
            <tbody>
            <% @sources.each do |item| %>
              <tr style="text-align: center;">
                <td><%= item.file_name %></td>
                <td><%= item.file_type %></td>
                <td><%= number_to_human_size item.file_size %></td>
                <td><a href="/<%= item.file_path %>"><%= item.file_name %></a></td>
                <td>
                  <a href="<%= edit_admin_file_source_path(item) %>" class="btn bg-green btn-flat">
                    <i class="glyphicon glyphicon-edit"></i>
                    编辑
                  </a>
                  <a href="<%= admin_file_source_path(item) %>" class="btn bg-red btn-flat" data-method="delete" data-confirm="确定删除车型品类吗？">
                    <i class="glyphicon glyphicon-trash"></i>
                    删除
                  </a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <%= will_paginate @sources, :class=>'apple_pagination' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/file_sources/new.html.erb
<%= content_for(:title,  '添加文件 | Master') %>
<section class="content-header">
  <h1>
    添加文件
  </h1>
  <ol class="breadcrumb">
    <li class="active"><i class="glyphicon glyphicon-plus"></i> 新增文件</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-success">
      <div class="box-header">
        <h3 class="box-title">新增表单</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section>